version: '3.8'

services:
  backend:
    image: mielola/golang-ticketing-main-backend:latest
    container_name: golang-ticketing-backend
    environment:
      - DB_HOST=mysql-ticketing
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=commandcenter
    ports:
      - "8083:8080"
    networks:
      - ticketing-network

  mysql-ticketing:
    image: mysql:5.7
    container_name: mysql-ticketing
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: commandcenter
    ports:
      - "3309:3306"
    networks:
      - ticketing-network
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: golang-ticketing-nginx
    ports:
      - "8082:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - ticketing-network

volumes:
  db_data:

networks:
  ticketing-network:
    external: true
