version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golang-ticketing-backend
    environment:
      - DB_HOST=golang-ticketing-db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=commandcenter
    ports:
      - "8083:8080"
    depends_on:
      - db
    networks:
      - ticketing-network

  db:
    image: mysql:5.7
    container_name: golang-ticketing-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: commandcenter
    ports:
      - "3309:3306"
    networks:
      - ticketing-network
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: golang-ticketing-nginx
    ports:
      - "8082:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - ticketing-network

volumes:
  db_data:

networks:
  ticketing-network:
    external: true
