CREATE TABLE tickets (
    id BIGINT(20) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    tracking_id VARCHAR(255) NOT NULL UNIQUE,
    hari_masuk DATE NOT NULL,
    waktu_masuk TIME NOT NULL,
    hari_respon DATE DEFAULT NULL,
    waktu_respon TIME DEFAULT NULL,
    nama_admin VARCHAR(255) DEFAULT NULL,
    email VARCHAR(255) NOT NULL,
    priority ENUM('low', 'medium', 'high', 'critical') NOT NULL,
    status VARCHAR(255) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    detail_kendala TEXT NOT NULL,
    owner VARCHAR(255) NOT NULL,
    time_worked INT(11) DEFAULT NULL,
    due_date DATE DEFAULT NULL,
    kategori_masalah VARCHAR(255) DEFAULT NULL,
    respon_diberikan TEXT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
