CREATE TABLE login_times (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL, 
    Login DATETIME NOT NULL,
    Logout DATETIME NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_login_user FOREIGN KEY (email) REFERENCES users(email) ON DELETE CASCADE
);
